#!/bin/bash

script=${0##*/}

usage() {

    cat << EOF

    usage: $script

    A script to update iptable records for dynamic dns hosts.

    Run this script in your cron table to update ips.

    You might want to put all your dynamic hosts in a separate chain,
    this way one can easily see what dynamic hosts are trusted.

    create the chain in iptables.
    /usr/sbin/iptables -N dyndns
    insert the chain into the input chain @ the head of the list.
    /usr/sbin/iptables -I INPUT 1 -j dyndns
    flush all the rules in the chain
    /usr/sbin/iptables -F dyndns

EOF
}

if [[ "$#" -eq "0" ]]; then
    usage
    exit 1
fi

HOST="$1"
CHAIN="dyndns"  ## change this to whatever chain you want.
IPTABLES="/usr/sbin/iptables"

## check to make sure we have enough args passed.
if [ -z "$1" ] ; then
    echo ""$0" hostname"
    echo "You must supply a hostname to update in iptables."
    exit
fi

"$IPTABLES" -L -n -v | grep "$CHAIN" > /dev/null
if [ "$?" -ne "0" ] ; then
    "$IPTABLES" -N "$CHAIN"
    "$IPTABLES" -I INPUT 1 -j "$CHAIN"
fi

for HOST in $* ; do

    HOSTFILE="/var/run/fw-dyndns/host-"$HOST""

    OLDIP=""
    if [ -a "$HOSTFILE" ]; then
        OLDIP=$(cat "$HOSTFILE")
        # echo "CAT returned: $?"
    fi

    IP=$(ping -c 1 "$HOST" | head -n 1 | awk '{print $3}' | tr -d "():")

    if [ "${#IP}" = "0" ]; then
        echo "Couldn't lookup hostname for "$HOST", failed."
        exit
    fi

    ## save new ip.
    echo "$IP">"$HOSTFILE"

    echo ""
    echo "Updating "$HOST" in iptables."
    if [ "${#OLDIP}" != "0" ]; then
        echo "Removing old rule ("$OLDIP")"
        $("$IPTABLES" -D "$CHAIN" -s "$OLDIP"/32 -j ACCEPT)
    fi

    echo "Inserting new rule ($IP)"
    $("$IPTABLES" -A "$CHAIN" -s "$IP"/32 -j ACCEPT)

done
