#!/bin/bash

script=${0##*/}

usage() {

    cat << EOF

    usage: $script

    Binary package update on a arch system.

EOF
}

if [[ "$#" -ne "0" ]]; then
    usage
    exit 1
fi

if [[ -e $HOME/mnt/donkey/.bashrc || $HOSTNAME == donkey ]]; then
    abs
    yaourt -Syu --aur
#    pacman --noconfirm -Rsn $(pacman -Qqtd)
    pacman-optimize
    sync
    echo "==> Sync Complete"
    find /etc -type f -name "*.pac*"
elif [[ -e /bin/mount ]]; then
    mount $HOME/mnt/donkey
else
    echo "Is donkey sshfs mounted?"
fi
