#!/bin/bash

script=${0##*/}

usage() {

    cat << EOF

    usage: $script

    rsync arch linux core and extra repos for i686 and x86_64
    architectures

EOF
}

if [[ "$#" -ne "0" ]]; then
    usage
    exit 1
fi


for repo in core extra; do
    for arch in i686 x86_64; do

        if [[ -d /mnt/raid/archive/archlinux/ ]]; then
            rsync -aPv rsync://mirror.csclub.uwaterloo.ca/archlinux/$repo/os/$arch /mnt/raid/archive/archlinux/$repo/os/ >> /var/log/crond 2>&1
        fi

    done
done
